### ISSUE TITLE
Support dependency tree of packages

### ISSUE THREAD

**Issue by coenjacobs** [coenjacobs/mozart#1]
At this point, the dependencies of a package you want to bundle inside your WordPress plugin are not handled. So, you need to specify them all in your `composer.json`, or they will not be moved into your own namespace. In future releases, I want to add support for looping through the tree of dependencies for each package to bundle, to automate this process.

**Comment by costasovo** [comment]
Hi I would like to try implement support for dependency tree. Here is my idea how to do it:

- get production dependencies and suggested dependencies for a package from composer.lock
- check if the dependency is really installed by looking in directory
- process the dependency same way as package
- update processed parent package code and set correct namespaces in use statements with the child dependency package

What do you think? I thought that maybe you already have some ideas/thoughts how to implement it...

**Comment by coenjacobs** [comment]
@costasovo Yes, that seems about right. I haven't thought too much about how I would build this and haven't written much code other than some now discarded experiments.

The one thing that requires the most work in my opinion, is keeping track of all the changed namespaces (and technically also global class names which might be renamed as well) and replacing these in all files of each dependency as well. This needs to happen in an organized way, featuring great test coverage as well to ensure this is reliable, before this can be released.

Any help in achieving this is greatly appreciated! 👍
