### ISSUE TITLE
Carbon Fields, including non-class files

### ISSUE THREAD

**Issue by MikeiLL** [coenjacobs/mozart#130]
HI Coen and devs.

I'm trying to include Carbon Fields, which looks like this:

```
vendor/htmlburger/carbon-fields
├── CONTRIBUTING.md
├── ISSUE_TEMPLATE.md
├── README.md
├── assets
├── bin
├── build
├── composer.json
├── config.php
├── core
├── languages
├── license.txt
├── package.json
├── packages
├── templates
├── webpack.config.js
└── yarn.lock
```

Where the autoload config is like this:

```
"psr-4": {
  "Carbon_Fields\\": "core/"
}
```

And Mozart is only putting the files from `core` into `src/Dependencies/Carbon_Fields`:

```
  "dep_namespace": "MZoo\\MzMboAccess\\Dependencies\\",
  "dep_directory": "/src/Dependencies/",
  "classmap_directory": "/src/Classes/",
  "classmap_prefix": "MZMBOACCESS_",
  "packages": [
      "htmlburger/carbon-fields"
  ]
```

I'm working with `override_autoload`, but may be misunderstanding how it's supposed to work:

```
"override_autoload": {
    "htmlburger/carbon-fields": {
      "psr-4": {
        "Carbon_Fields\\": "core/"
      },
      "files": [
        "config.php", 
        "templates",
        "assets",
        "build"
      ]
    }
}
```

Still, only the contents of `core` are copied.

If I set 

```
      "psr-4": {
        "Carbon_Fields\\": "./"
      },
```

All files are copied, but with incorrect namespaces.

Wondering if I should just be manually including the `config.php, templates, assets, build` and hoping someone here has some insight into the problem.

**Comment by MikeiLL** [comment]
# Update

If I add a sub-namespace, the files are added within a directory matching it, however, with multiple sub-namespaces, only the last directory is present:

```
"psr-4": {
  "Carbon_Fields\\core\\": "core/",
  "Carbon_Fields\\assets\\": "assets/",
  "Carbon_Fields\\languages\\": "languages/",
  "Carbon_Fields\\templates\\": "templates/"
}
```

```
ls src/Dependencies/Carbon_Fields
templates
```

**Comment by BrianHenryIE** [comment]
Your understanding of `override_autoload` is not incorrect, it's just that Mozart does not handle `files` autoloaders.

There are two solutions in draft PRs that could help anyway.

#60 "Generate classmap" adds a `mozart dump-autoload` command which adds a classmap in the root of your `dep_directory` and `classmap_directory` which you can use instead of PSR-4 autoloading.

#63 "Return one Autoloader per namespace" addresses the issue where you have defined the list of directories to autoload but only one is being used.

Normally I'd suggest using [cweagans/composer-patches](https://github.com/cweagans/composer-patches) to apply the PRs to master in composer but that's not working for either of them. I do have a branch with both those issues resolved and which handles `files`. You can use the following and just `require_once __DIR__ . '/src/mozart/autoload.php';` and you should be good to go:

```
{
  "require": {
    "htmlburger/carbon-fields": "*"
  },
  "repositories": [
    {
      "url": "https://github.com/brianhenryie/mozart",
      "type": "git"
    }
  ],
  "require-dev":{
    "coenjacobs/mozart": "dev-rewrite"
  },
  "extra": {
    "mozart":{
      "dep_namespace": "MZoo\\MzMboAccess\\",
      "dep_directory": "/src/mozart/",
      "override_autoload": {
        "htmlburger/carbon-fields": {
          "psr-4": {
            "Carbon_Fields\\": "core/"
          },
          "files": [
            "config.php",
            "templates",
            "assets",
            "build"
          ]
        }
      }
    }
  }
}
```

**Comment by MikeiLL** [comment]
Thank you so much, @BrianHenryIE. Will get more into it tomorrow. 

The `templates`, `assets` and `build` dirs are there in `src/mozart`, but not `config.php`.

It seems to be generating the prefixed namespaces, but Composer is also complaining with a number of these:

```
Class MZoo\MzMboAccess\Carbon_Fields\Container located in ./src/mozart/htmlburger/carbon-fields/core/Container.php does not comply with psr-4 autoloading standard.
```

Am thinking maybe something is wrong with cases of the copied directory and perhaps file names.

**Comment by BrianHenryIE** [comment]
For me, `config.php` is definitely being copied (and its namespace prefixed). I just copied and pasted the `composer.json` from my last reply and deleted the target directory and everything worked as expected.

I'm not sure what exactly you're doing that is prompting that error, but with this setup, the `src/mozart` directory does not need to be PSR-4 autoloaded. What command are you running that is outputting that error? I'm guessing maybe `composer dump-autoload` – that is already run during the `mozart compose` command. It shouldn't be a problem during you application runtime. But I would like to replicate and understand it.

It might just be a matter of adding `"MZoo\MzMboAccess\Carbon_Fields": "src/mozart/htmlburger/carbon-fields/core/"` to your `composer.json` autoload key.

**Comment by MikeiLL** [comment]
Hmm. Getting this error now: `Composer could not find the config file: /Path/To/vendor/composer-plugin-api/composer.json`, which from what I'm googling has to do with an environment variable. I'm not sure where it's set yet.

Yes, had been running `dump-autoload` in 

```
    "post-update-cmd": [
      "\"vendor/bin/mozart\" compose"
    ]
```

Removed now.

What do you mean `composer.json` autoload key?

This is my entire composer.json file in case you see anything I might be missing:

```
{
	"name": "mikeill/mz-mbo-access",
	"description": "Grant Client Access Based on Mindbody Online API Credentials",
	"keywords": [
    "MBO",
    "mindbody",
    "wordpress",
    "plugin",
    "session"
  ],
  "prefer-stable": true,
	"homepage": "https://github.com/MikeiLL/mz-mbo-access",
	"license"          : "GPL-2.0-or-later",
	"minimum-stability": "dev",
	"authors": [
    {
      "name": "Mike iLL Kilmer",
      "email": "mike@mzoo.org",
      "homepage": "http://mzoo.org",
      "role": "Developer"
    }
   ],
   "repositories": [
     {
       "url": "https://github.com/brianhenryie/mozart",
       "type": "git"
     }
    ],
	"type": "wordpress-plugin",
	"require": {
		"php": ">=7.1",
		"composer/installers": "~1.0",
		"ericmann/sessionz": "^0.3",
		"htmlburger/carbon-fields": "^3.3"
	},
	"config": {
	  "optimize-autoloader": true,
	  "preferred-install": "dist",
	  "sort-packages": true
	},
	"scripts": {
		"lint": [
		  "phpcs --extensions=php src *.php"
		],
    "fix": ["phpcbf --extensions=php src *.php"],
    "post-install-cmd": [
        "\"vendor/bin/mozart\" compose"
    ],
    "post-update-cmd": [
      "\"vendor/bin/mozart\" compose"
    ]
	},
	"autoload": {
		"psr-4": {
			"MZoo\\MzMboAccess\\": "src",
			"EAMann\\": "libraries/wp-sessions",
			"EAMann\\WPSession\\": "libraries/wp-sessions",
			"EAMann\\WPSession\\Objects\\": "libraries/wp-sessions"
		}
	},
  "extra": {
    "mozart":{
      "dep_namespace": "MZoo\\MzMboAccess\\",
      "dep_directory": "/src/mozart/",
      "override_autoload": {
        "htmlburger/carbon-fields": {
          "psr-4": {
            "Carbon_Fields\\": "core/"
          },
          "files": [
            "config.php",
            "templates",
            "assets",
            "build"
          ]
        }
      }
    }
  },
  "require-dev": {
		"coenjacobs/mozart": "dev-rewrite",
		"squizlabs/php_codesniffer": "*",
		"wp-coding-standards/wpcs": "*"
	}
}

```

**Comment by BrianHenryIE** [comment]
I noticed that but I don't think it's important. I hadn't seen it before today so I'm not 100% sure what's up. `functions.php` is copied and prefixed correctly.

With: `"delete_vendor_directories": false,` the message does not appear. I'm guessing loop to delete the files is deleting the directory and then trying to delete the file which no longer exists.

**Comment by BrianHenryIE** [comment]
If your `composer.json` `/extra/mozart` does not have a `packages` key, it uses the `require` key to determine which packages to process. So adding:
```
"packages": [
  "htmlburger/carbon-fields"
],
```
should address that.

**Comment by MikeiLL** [comment]
Ah. Cool. I think it had had a "packages" key at first, and now does again. I've also been managing Eric Mann's Sessions with Composer, which at the moment I'm excluding. but may see if I can get it to play with Mozart as well.

At the moment you seem to have provided the needed miracle with:

```
"mozart":{
      "dep_namespace": "MZoo\\MzMboAccess\\Dependencies\\",
      "dep_directory": "/src/mozart/",
      "exclude_packages": [
          "ericmann/sessionz"
      ],
      "packages": [
        "htmlburger/carbon-fields"
      ],
      "delete_vendor_directories": false,
      "override_autoload": {
        "htmlburger/carbon-fields": {
          "psr-4": {
            "Carbon_Fields\\": "core/"
          },
          "files": [
            "config.php",
            "templates",
            "assets",
            "build"
          ]
        }
      }
    }
```

**Comment by MikeiLL** [comment]
Here is the composer config by which I am, using [Brian Henry's fork](https://github.com/brianhenryie/mozart) to include Eric Mann's Sessionz and WP_Session_Manager and Carbon Fields via Mozart. (A little night music plays in the background.)

```
	"type": "wordpress-plugin",
	"scripts": {
		"lint": [
		  "phpcs --extensions=php src *.php"
		],
    "fix": ["phpcbf --extensions=php src *.php"],
    "post-install-cmd": [
        "\"vendor/bin/mozart\" compose"
    ],
    "post-update-cmd": [
      "\"vendor/bin/mozart\" compose"
    ]
	},
  "require": {
		"php": ">=7.1",
		"ericmann/sessionz": "^0.3",
		"ericmann/wp-session-manager": "*",
    "htmlburger/carbon-fields": "*"
  },
  "repositories": [
    {
      "url": "https://github.com/brianhenryie/mozart",
      "type": "git"
    },
    {
      "url": "https://github.com/ericmann/wp-session-manager",
      "type": "git"
    }
  ],
  "require-dev":{
    "coenjacobs/mozart": "dev-rewrite",
		"squizlabs/php_codesniffer": "*",
		"wp-coding-standards/wpcs": "*"
  },
	"autoload": {
		"psr-4": {
			"MZoo\\MzMboAccess\\": "src"
		}
	},
  "extra": {
    "mozart":{
      "dep_namespace": "MZoo\\MzMboAccess\\Dependencies\\",
      "dep_directory": "/src/Mozart/",
      "packages": [
        "htmlburger/carbon-fields",
        "ericmann/wp-session-manager",
        "ericmann/sessionz"
      ],
      "delete_vendor_directories": false,
      "override_autoload": {
        "htmlburger/carbon-fields": {
          "psr-4": {
            "Carbon_Fields\\": "core/"
          },
          "files": [
            "config.php",
            "templates",
            "assets",
            "build"
          ]
        }
      }
    }
  }
```
