### ISSUE TITLE
Cannot use with interoperability standards

### ISSUE THREAD

**Issue by XedinUnknown** [coenjacobs/mozart#15]
Not so much an issue, but a note.

If you write good code, you follow [SOLID][] whenever you can. This means that you depend on abstractions, not concretions, and requires interfaces. In these cases, you cannot use the approach of this package, because if you depend on `A\B\C`, then this is exactly the [FQCN][] that must be depended on, and exactly the dependency that must be satisfied. If my method accepts a [`Dhii\Output\TemplateInterface`][], it cannot suddenly be provided with a `CoenJacobs\My\OtherInterface` instance; nor should I change my method to rely on `CoenJacobs\My\OtherInterface`. If you use interfaces, and try to standardize things in your code - such as by using [interoperability standards][PSR] (and you should) - then this is inevitably the problem you will encounter. That is because FQCNs should by design be globally unique, and constant - because that is how their author decided they should be, and other code depends on it to be that way.

Therefore, unfortunately, Mozart is not a solution if you are really looking to re-use existing solutions. But it may solve you problem if you only depend on your own code, and do not follow best practices.

[`Dhii\Output\TemplateInterface`]: https://github.com/Dhii/output-renderer-interface/blob/develop/src/TemplateInterface.php
[PSR]: https://www.php-fig.org/psr/
[SOLID]: https://en.wikipedia.org/wiki/SOLID
[FQCN]: https://en.wikipedia.org/wiki/Fully_qualified_name

**Comment by coenjacobs** [comment]
I absolutely agree. In fact, at the initial release of this package, I called [Mozart a monkey patch](https://coenjacobs.me/2017/03/07/mozart-monkey-patches-wordpress-lack-dependency-management/) myself. I'm fully aware this is breaking a bunch of coding best practices, but unfortunately this is the least evil way to solve the issue at hand.

**Comment by XedinUnknown** [comment]
Thank you very much for this reply, I appreciate it.
