### ISSUE TITLE
Classname in `class_exists` check not replaced

### ISSUE THREAD

**Issue by mundschenk-at** [coenjacobs/mozart#16]
I've got a PHP 5.2 compatible class in a dependency (loaded manually via include) that's defined inside a `if ( ! class_exists( 'CLASSNAME' ) ) {` fence. The class name in the class definition is prefixed, the one in the conditional is not.

**Comment by coenjacobs** [comment]
Closing this in favour of #13 as it is essentially the same issue. Will work on fixing this before we go towards the Mozart 1.0 release soon.
