### ISSUE TITLE
No duplicate detection for dependencies loaded via classmaps

### ISSUE THREAD

**Issue by mundschenk-at** [coenjacobs/mozart#17]
My project a direct dependency `A` and a direct dependency `B` that also depends on `A`. Both are loaded via classmaps and not PSR-4 (because they follow the WordPress class filename convention).

`vendor/bin/mozart compose` now results in the following error message:

```
In Filesystem.php line 405:
                                                                               
  File already exists at path: <relative-path-to-A>/<A>.php                                           
```

**Comment by coenjacobs** [comment]
Thanks for reporting this. I think #19 will fix this issue, going in next fix release.
