### ISSUE TITLE
No duplication checking is made during the copy.

### ISSUE THREAD

**Issue by heera** [coenjacobs/mozart#23]
When trying to compose `Illuminate\Database: 5.0.0`, the following exception is being thrown:
<img width="776" alt="Screen Shot 2019-04-02 at 1 22 52 AM" src="https://user-images.githubusercontent.com/1007324/55353798-01262880-54e6-11e9-8900-6b4bc4a95ff4.png">

Seems like two dependent packages have same package file as their dependencies and once the files is moved for the first time, then the second time it doesn't copy, nor it does escape it.

**Comment by coenjacobs** [comment]
This is fixed via #19, soon to be released.
