### ISSUE TITLE
Run mozart over already existing wordpress composer-enabled plugins?

### ISSUE THREAD

**Issue by Xilonz** [coenjacobs/mozart#28]
I've ran acros an issue where 2 plugins use the same dependency, but on a different major verion. I understand that mozart is made for plugin-authors to prevent such issues.

Is there a way to run mozart over the wordpress-plugins to resolve plugin conflicts? And is this something mozart could offer out-of-the-box?

I'm using [Roots Bedrock](https://github.com/roots/bedrock/) so all plugins are composer dependencies.

**Comment by coenjacobs** [comment]
Mozart is a developers tool and should be implemented by the specific plugins developer. As soon as Bedrock is loading in the dependencies, it is _very_ hard to run the logic there and possibly impossible with Mozart in its current state.

As you stated yourself, this is not a goal for the near future of Mozart to work this way, so I'm going to close this issue. Developers are able to solve this for their own plugin, but I doubt there is a proper way we can ever support this for an entire installation.
