### ISSUE TITLE
Question on Usage

### ISSUE THREAD

**Issue by wunderdojo** [coenjacobs/mozart#29]
I just came across this and added it to a plugin. Wasn't totally clear on what the classmap_directory config setting was for. In my config. I have Mozart putting the bundled packages in /src/packages. The classmap_directory is set to /src/composer which just creates an empty folder. In my build script I then copy /vendor/autoload.php and /vendor/composer/* to the /src and /src/composer folders respectively.

It's all working great, but I'm wondering if I'm misunderstanding the intended usage of classmap_directory. 

Thanks a ton for the tool. Having run into the issue with other plugins requiring older versions of the same package this is a real help.

**Comment by Grapestain** [comment]
I've just tried Mozart myself today, so I'm in no way expert, but I think I can shed some light: 

Based on what I saw the `classmap_directory` is used only for Classes that are not in any namespace originally in their Composer package. These Classes are not going to have their namespaces prefixed, as they haven't got one to start with. Instead they will have their classnames prefixed with the `classmap_prefix` value and moved into the `classmap_directory` folder.
If all your packages use proper namespacing to start with, the `classmap_directory` will stay empty.

**Comment by coenjacobs** [comment]
The answer @Grapestain gave is 100% correct. This is also why this note is added in `README.md`:

>>>Important: Since Mozart automatically processes the full dependency tree of the packages you specify, you need to specify all these configuration options, because you can't reliably determine what kind of autoloaders are being used in the full dependency tree. A package way down the tree might suddenly use a classmap autoloader for example. Make sure you also include the namespace directory and classmap directory in your own autoloader, so they are always loaded.
