### ISSUE TITLE
Setting delete_vendor_directories to false doesn't seem to work.

### ISSUE THREAD

**Issue by danieliser** [coenjacobs/mozart#50]
`"delete_vendor_directories": false` doesn't seem to work for me.

Given the example below: https://gist.github.com/danieliser/2a0af213ec608c216bddc7cc7fa76df7

After `composer update` or `composer install`

**Comment by coenjacobs** [comment]
Is this on the 0.6 beta releases? The README in the `master` branch represents that release and not the actual stable 0.5 release.

**Comment by BrianHenryIE** [comment]
It’s 0.5.1

**Comment by danieliser** [comment]
@BrianHenryIE - I think it may be related to another issue I mentioned to @coenjacobs  on Twitter. Specifically loading the `nesbot/carbon` library was mucking it all up I think. It seems to be working without that lib.

Specifically when we tried to parse that package:
1. Namespaces got messed up, instead of `My\Dependencies\Pimple\Container`, we were getting `Pimple\ContainerMy\Dependencies\` which is clearly wrong.
2. It was deleting the files from vendor.

No idea why, would love to know though.

**Comment by coenjacobs** [comment]
Closing this, because the functionality referred to is actually part of the upcoming 0.6 release. Made a separate issue about the namespace messing up in #53.
