### ISSUE TITLE
Persist a .gitkeep file in classmaps directory

### ISSUE THREAD

**Issue by markjaquith** [coenjacobs/mozart#51]
If your specific Composer/Mozart install doesn't have any classmaps, Mozart will generate an empty classmaps directory, and delete any other files in it. But then you can't check that directory in (because Git only knows about files, not directories). And because you can't check that directory in, a `composer install` after a `git clone` will generate a `RuntimeException`:

>  [RuntimeException]
>  Could not scan for classes inside "lib/classmaps/" which does not appear to
>  be a file nor a folder

Normally I'd solve this by putting a `.gitkeep` file in my classmaps directory. But Mozart deletes that after every `composer update` run, so now the working directory has unnecessary changes that I don't want to check in.

I think my ideal solution here would be for Mozart to ignore non-PHP files in the classmaps directory. That'd allow me to persist a `.gitkeep`, which would ensure that the directory always exists.

**Comment by BrianHenryIE** [comment]
Mark, I think my PR #55 addresses your need.

But, TBH, I don't actually understand your real problem. Can you post a composer.json that I can use to reproduce the `RuntimeException` problem. I admit, and maybe it's because of my [lack of] understanding of PSR-x/classmap, I'm struggling to see where exactly the error is being generated.

**Comment by markjaquith** [comment]
@BrianHenryIE Answered more fully here! https://github.com/coenjacobs/mozart/pull/55#issuecomment-642857824

Here is the minimal `composer.json` file to reproduce the issue:

```json
{
    "name": "markjaquith/test",
    "autoload" : {
        "classmap": [
            "classes"
        ]
    }
}
```

Drop that as `composer.json` in an empty directory (i.e. do NOT create `classes` subdirectory) and run `composer install`.

>   [RuntimeException]
>  Could not scan for classes inside "classes" which does not appear to be a file nor a folder
