### ISSUE TITLE
Sub-dependencies are not processed correctly.

### ISSUE THREAD

**Issue by rilwis** [coenjacobs/mozart#75]
I'm trying to change the namespace for `Twig` and here is my `composer.json`:

```
"mozart": {
	"dep_namespace": "MBViews\\Dependencies\\",
	"dep_directory": "/src/Dependencies/",
	"classmap_directory": "/classes/dependencies/",
	"classmap_prefix": "MBV_",
	"packages": [
		"twig/twig"
	],
	"override_autoload": {},
	"delete_vendor_directories": true
}
```

And here is the screenshot of the `Dependencies` folder, which looks quite right. Twig and Symfony packages are moved correctly.

![image](https://user-images.githubusercontent.com/668274/96537685-15489b00-12c1-11eb-9e33-6be8cd410d60.png)

However, inside the `Dependencies/Symfony/Polyfill/Mbstring/bootstrap.php` file, there's are lines like this:

```php
use Symfony\Polyfill\Mbstring as p;

if (!function_exists('mb_convert_encoding')) {
    function mb_convert_encoding($s, $to, $from = null) { return p\Mbstring::mb_convert_encoding($s, $to, $from); }
}

// More lines
```

Note the `use` statement here. It should prepended with our configuration in the `composer.json`, which should be `MBViews\Dependencies\Symfony\Polyfill\Mbstring`.

Currently, I manual change it, because there're only 2 packages from Symfony need to change. But if there're many packages, the work will be huge.

**Comment by coenjacobs** [comment]
@rilwis Can you perhaps try again with the current `master` branch, now that some of the more matured recursive package fixes have been merged, so I expect this to be fixed. If not, could you please provide your entire `composer.json` file here?

**Comment by rilwis** [comment]
@coenjacobs I just got a chance to try mozart again and looks like this issue is fixed!

Thanks for your library.

**Comment by coenjacobs** [comment]
Glad to hear that @rilwis - happy it's serving you well!
