### ISSUE TITLE
Replacements in tree are only touching the direct parent

### ISSUE THREAD

**Issue by coenjacobs** [coenjacobs/mozart#80]
Imagine the following scenario:

1. Package A requires package B
2. Package B requires package C
3. Classes from package C are being used in package A
4. Package A is used by my plugin, rewriting with Mozart

What happens next, when `mozart compose` runs:

1. Package B classes in package A code are being replaced
2. Package C classes in package B code are being replaced
3. Package C classes in package A code are **not** being replaced

I've found this problem in [`picqer/moneybird-php-client`](https://github.com/picqer/moneybird-php-client/), which requires [`guzzlehttp/guzzle`](https://github.com/guzzle/guzzle). The latter package then requires [`php-fig/http-client`](https://github.com/php-fig/http-client), which is ultimately being used in one of the `picqer/moneybird-php-client` classes. For example in the [`Connection` class using `ResponseInterface`](https://github.com/picqer/moneybird-php-client/blob/85de7d410ae815189278c8cd65a7a37cd496fd03/src/Picqer/Financials/Moneybird/Connection.php#L14).

We can arguably say that it's wrong to use classes that are not in your own dependencies, but I think this happens more often than this specific example I've found. I'm going to submit a pull request to the `picqer/moneybird-php-client` package, to get this resolved anyway, but I would love to make this work for Mozart out of the box, without changes to remote code.

This will probably require some extensive changes to the way we now handle the dependency tree, but what it ultimately comes down to seem fairly straight forward to me: All replacements done to class definitions in a package, need to be replaced in the **entire tree** of packages that depend on those packages. So from the example above, replacements made in package C, need to be done in package B and package A as well.

**Comment by BrianHenryIE** [comment]
This seems to be the same issue as #58

**Comment by coenjacobs** [comment]
This is resolved by merging in #82.
